### ISSUE TITLE
PriorityBlockingQueue - problem with getting the field offset on a hidden class.

### ISSUE THREAD

**Issue by Asinrus** [JetBrains/lincheck#340] opened 2024-07-15 14:54 UTC
Hello Lincheck Team
Thank you for your product. It is a great tool. 

I'm reaching out to you to ask about a strange behavior that I hit during the implementation of an LFU cache and I thought you would find it interesting. 
Tech - java-correto-17.0.8 , lincheck-2.32
My local setup - MacOs 14.5 (23F79), Apple M1 Pro, 
Link to the repo  - https://github.com/Asinrus/lincheck-priority-queue-check 

As you can see in class CacheLFUService I made a simple implementation with PriorityBlockingQueue and ConcurrentHashMap. 

To check the correctness of my program I made two tests: 
1. me.asinrus.CacheLFUServiceTest#modelCheckingTest2threads - the test is passed.
2. me.asinrus.CacheLFUServiceTest#modelCheckingTest3threads - test is failing 
Additionally in this case, I see in the logs 
```
java.lang.UnsupportedOperationException: can't get field offset on a hidden class: private final java.util.function.ToIntFunction java.util.Comparator$$Lambda$273/0x000000f80106f0c0.arg$1
	at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:645)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.FieldSearchHelper.findObjectField(FieldSearchHelper.kt:109)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.FieldSearchHelper.findObjectField(FieldSearchHelper.kt:79)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.FieldSearchHelper.findObjectField(FieldSearchHelper.kt:79)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.FieldSearchHelper.findObjectField(FieldSearchHelper.kt:79)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.FieldSearchHelper.findFinalFieldWithOwner$lincheck(FieldSearchHelper.kt:39)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.findOwnerName(ManagedStrategy.kt:1305)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.createBeforeMethodCallTracePoint(ManagedStrategy.kt:1166)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.beforeMethodCall(ManagedStrategy.kt:1125)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.beforeMethodCall(ManagedStrategy.kt:966)
	at sun.nio.ch.lincheck.Injections.beforeMethodCall(Injections.java:257)
	at me.asinrus.CacheLFUService.put(CacheLFUService.java:71)
	at me.asinrus.CacheLFUServiceTest.put(CacheLFUServiceTest.java:16)
	at org.jetbrains.kotlinx.lincheck.runner.TestThreadExecution130.run(Unknown Source)
```
So, it looks like the Lincheck can't handle the test cases with a priorityQueue class.
Can you have a look?

**Comment by ndkoval** [comment] 2024-09-09 16:12
Hi @Asinrus, could you please check whether the problem is fixed in Lincheck 2.34?

**Closed** 2024-09-23 13:15 UTC
Labels: bug
