### ISSUE TITLE
UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)

### ISSUE THREAD

**Issue by lukaszkalnik** [JetBrains/lincheck#334] opened 2024-06-12 12:03 UTC
I integrated the example `BasicCounterTest` from the [tutorial](https://kotlinlang.org/docs/introduction.html#write-a-concurrent-counter-and-run-the-test) into my Android project and when trying to run it I get the following exception:
```java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)```

I have the dependency for lincheck 2.32 and JUnit 5.10.2. I'm on Kotlin 2.0.

When I create a new project with the same dependencies, the test works as expected. 
My current project setup is quite complex, although I don't have any problems with other JUnit5 and JUnit4 tests there.

I have `useJUnitPlatform()` in my `build.gradle.kts` `android` block.

Any hints on what I should look into to fix the issue? Thank you!

**Comment by ndkoval** [comment] 2024-06-23 16:52
Hi @lukaszkalnik, do you use Java agents when running the tests?

**Comment by ndkoval** [comment] 2024-07-09 16:16
@lukaszkalnik, could you please provide a reproducer, please?

**Comment by ndkoval** [comment] 2024-07-09 17:23
@lukaszkalnik, I would be happy to help with your issue, but it is difficult without a reproducer or any specific input about the environment. Since the issue does not look relevant to you at the moment, and the required information cannot be provided, I'm closing it.

**Closed by ndkoval** 2024-07-09 17:23 UTC
