### ISSUE TITLE
Testing blocking operations

### ISSUE THREAD

**Issue by adamw** [JetBrains/lincheck#236] opened 2023-10-05 16:31 UTC
The following is more of a question, than a bug report: if there's a better place to ask questions, please excuse me and point me in the right direction :)

I'm trying to use lincheck to test some blocking code, using Java 21 & Loom under the hood. The first step to make lincheck work at all was to bump the version of ASM to 9.6, but with this out of the way, things seemed promising: the examples from the documentation worked fine.

However, lincheck doesn't support testing (interruptible) blocking code out of the box. However, we've got suspension support - so I'm trying to use that. Here's my attempt at testing Java's `SynchronousQueue`:

```scala
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runInterruptible
import org.jetbrains.kotlinx.lincheck.annotations.Operation
import org.jetbrains.kotlinx.lincheck.annotations.Param
import org.jetbrains.kotlinx.lincheck.check
import org.jetbrains.kotlinx.lincheck.paramgen.IntGen
import org.jetbrains.kotlinx.lincheck.strategy.stress.StressOptions
import org.junit.*
import java.util.concurrent.SynchronousQueue

@Param(name = "value", gen = IntGen::class, conf = "1:9")
class BasicQueueTest {
  private val c = SynchronousQueue<Int>()

  @Operation(blocking = true, allowExtraSuspension = true)
  suspend fun send(@Param(name = "value") v: Int) = runInterruptible(Dispatchers.IO) { c.put(v) }

  @Operation(blocking = true, allowExtraSuspension = true)
  suspend fun receive() = runInterruptible(Dispatchers.IO) { c.take() }

  @Test
  fun stressTest () = StressOptions().check(this::class)
}
```

When running, I get quite surprising results. Either the test hangs, throwing an exception due to usage of `Thread.stop` (which is fixed in [this PR](https://github.com/JetBrains/lincheck/pull/214)), or produces an output such as:

```
Test BasicQueueTest.stressTest failed: org.jetbrains.kotlinx.lincheck.LincheckAssertionError:
= Invalid execution results =
| ---------------------------------------------------- |
|         Thread 1         |         Thread 2          |
| ---------------------------------------------------- |
| receive(): SUSPENDED + 6 | send(6): SUSPENDED + void |
| ---------------------------------------------------- |
, took 1.194s
    at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.kt:38)
    at org.jetbrains.kotlinx.lincheck.LinChecker$Companion.check(LinChecker.kt:144)
    at org.jetbrains.kotlinx.lincheck.LinCheckerKt.check(LinChecker.kt:159)
    at org.jetbrains.kotlinx.lincheck.LinCheckerKt.check(LinChecker.kt:168)
```

This prompts the questions:

* what's the `+` in the results? The execution looks correct to me
* is my attempt at testing blocking code valid at all?

Thanks!

**Comment by adamw** [comment] 2023-10-07 09:04
@ndkoval sorry for the direct mention, but maybe you would have some insights if my attempts to use lincheck are correct at all? :)

**Comment by eupp** [comment] 2023-10-10 10:07
Hi @adamw !

- `SUSPENDED + x` notation means that the suspending function was suspended during the execution, but then resumed and returned the value `x` as a result
- Regarding your test. I think that you should not call `runInterruptible(Dispatchers.IO)` by yourself. Internally, the framework takes care of suspending functions and sets up its own proper runner. You can take a look at the `[RendezvousChannelTest](https://github.com/JetBrains/lincheck/blob/master/src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/linearizability/RendezvousChannelTest.kt)` as a reference of lincheck test for suspending operations.

**Comment by eupp** [comment] 2023-10-10 16:45
> As for the first point - do you know then why the test fails? There doesn't seem to be anything wrong with suspending and returning 6 (or void) per se.

By default, Lincheck checks the data structure for linearizability. Receiving a parallel execution results, like the one in your example:

```
| ---------------------------------------------------- |
|         Thread 1         |         Thread 2          |
| ---------------------------------------------------- |
| receive(): SUSPENDED + 6 | send(6): SUSPENDED + void |
| ---------------------------------------------------- |
```

it would try to find a linearization that, when executed sequentially, gives the same results. 
In your example there are two possible candidate linearizations: `receive() ; send(6)` and `send(6) ; receive()`.
Since the `Invalid execution results` error appears, the framework has failed to reproduce the same results for both variants.

I still believe the issue is due to ` runInterruptible(Dispatchers.IO)`. 
When executing the tests, lincheck creates a its own internal thread for each thread of generated scenario. 
It does not know anything about any external threads (like `IO` threads from `Dispatchers.IO`) and has no control over them. 

It could be the case that when the scenario is executed in parallel and then sequentially (during linearization search), the threads in `Dispatchers.IO` are scheduled differently thus leading to different execution results --- a situation treated as an error by lincheck.

**Comment by eupp** [comment] 2023-10-11 18:22
@adamw 

I was able to successfully run your test by applying few modifications to it:

```kotlin
@Param(name = "value", gen = IntGen::class, conf = "1:9")
class BasicQueueTest {
    private val c = SynchronousQueue<Int>()

    @Operation(blocking = true, allowExtraSuspension = true)
    suspend fun send(@Param(name = "value") v: Int) = runInterruptible { c.put(v) }

    @Operation(blocking = true, allowExtraSuspension = true)
    suspend fun receive() = runInterruptible { c.take() }

    @Test
    fun stressTest () = StressOptions()
        .addCustomScenario {
            parallel {
                thread {
                    actor(::receive)
                }
                thread {
                    actor(::send, 5)
                }
            }
        }
        .iterations(0)
        .invocationsPerIteration(1000)
        .sequentialSpecification(SequentialSynchronousQueue::class.java)
        .check(this::class)
}

@OptIn(InternalCoroutinesApi::class)
class SequentialSynchronousQueue : SequentialIntChannel(capacity = 0)
```

- I used just `runInterruptible` without `IO` dispatcher, so that no external IO threads are used to run continuations. 
- I provided a separate class that implements "sequential specification" of a rendevouz `SynchronousQueue`:

```
.sequentialSpecification(SequentialSynchronousQueue::class.java)
```

With this option, Lincheck will use the class `SequentialSynchronousQueue` when searching for linearization, instead of the original class `BasicQueueTest` (note that two class should have same API for all methods marked as `Operation`). 

You can find the definition of `SequentialIntChannel` [here](https://github.com/JetBrains/lincheck/blob/master/src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/linearizability/SequentialIntChannel.kt). 
We use it inside our internal lincheck tests for testing channel-like data structures. 

Perhaps, we should make `SequentialIntChannel` a part of public API, so that the users can also use it to test their data structures implementing the channel interface. @ndkoval what do you think?

@adamw for now, the simplest solution for you could be just copy-pasting the implementation of `SequentialIntChannel` into your tests.

**Comment by adamw** [comment] 2023-10-12 12:37
@eupp Thanks a lot for the investigation :)

I copied your code, but when I change `iterations` to something more than `0`, the test hangs (or I get an exception due to usage of `Thread.stop`, if I use a version w/o PR #214 applied). 

I see how using the sequential specification might help, although it also uses suspendable functions, so I thought that's more of an additional validation to check against a straightforward implementation which doesn't have to be thread-safe, rather than a requirement to test suspendable functions in the first place.

**Closed** 2024-01-19 11:30 UTC
Labels: question

**Comment by adamw** [comment] 2024-01-19 13:21
@eupp thanks for the answers :) though @ndkoval just closed this as not planned, not sure how this relates to #143 then?

**Comment by eupp** [comment] 2024-01-19 14:33
@adamw I think it's more of a "this issue boils down to several existing issues" than "not planned".
